# Databricks notebook source
# Auto-generated by Agent 03A (Coding Agent) — RETRY 2
# Request: DBXCOE-24 | Plan: f20e39b469eda07f | Approved: auto_approved (system:auto_approve)
# Report: AgentOps Weekly Facility Report | Target: agentops.gold.agentops_weekly_facility_report
# Generated: 2026-09-30T15:37:59.936800+00:00 | Recommendation: modify_existing
# ---------------------------------------------------------------

from pyspark.sql import functions as F
from pyspark.sql import Window

# =========================
# Load bronze tables (spark session is available as 'spark')
# =========================
enc_bronze = spark.table("agentops.bronze.encounter").alias("enc_bronze")
clm_bronze = spark.table("agentops.bronze.claim").alias("clm_bronze")
org_bronze = spark.table("agentops.bronze.organization").alias("org_bronze")
pat_bronze = spark.table("agentops.bronze.patient").alias("pat_bronze")

# =========================
# Parse Encounter JSON fields and prepare Encounter facts
# =========================
enc_parsed = (
    enc_bronze
    # Extract JSON fields from raw_json per rule
    .withColumn("enc_status", F.get_json_object(F.col("enc_bronze.raw_json"), "$.status"))
    .withColumn("enc_class_code", F.get_json_object(F.col("enc_bronze.raw_json"), "$.class.code"))
    .withColumn("enc_subject_ref", F.get_json_object(F.col("enc_bronze.raw_json"), "$.subject.reference"))
    .withColumn("enc_service_provider_ref", F.get_json_object(F.col("enc_bronze.raw_json"), "$.serviceProvider.reference"))
    .withColumn("enc_period_start_raw", F.get_json_object(F.col("enc_bronze.raw_json"), "$.period.start"))
    .withColumn("enc_period_end_raw", F.get_json_object(F.col("enc_bronze.raw_json"), "$.period.end"))
    # Parse timestamps using data profile (ISO 8601 -> to_timestamp)
    .withColumn("enc_period_start_ts", F.coalesce(F.try_to_timestamp(F.col("enc_period_start_raw"), F.lit("MM/dd/yyyy HH:mm")), F.try_to_timestamp(F.col("enc_period_start_raw"))))
    .withColumn("enc_period_end_ts", F.coalesce(F.try_to_timestamp(F.col("enc_period_end_raw"), F.lit("MM/dd/yyyy HH:mm")), F.try_to_timestamp(F.col("enc_period_end_raw"))))
    # Derive join keys by stripping prefixes like "Patient/" or "Organization/"
    .withColumn("enc_patient_id", F.when(F.col("enc_subject_ref").isNotNull(), F.regexp_replace(F.col("enc_subject_ref"), "^.*?/", "")).otherwise(F.lit(None)))
    .withColumn("enc_org_id", F.when(F.col("enc_service_provider_ref").isNotNull(), F.regexp_replace(F.col("enc_service_provider_ref"), "^.*?/", "")).otherwise(F.lit(None)))
    # Encounter identifier from bronze table
    .withColumn("encounter_id", F.col("enc_bronze.resource_id"))
    # Inpatient flag based on class code "IMP"
    .withColumn("is_inpatient", F.when(F.upper(F.col("enc_class_code")) == F.lit("IMP"), F.lit(1)).otherwise(F.lit(0)))
    # Length of stay in days (non-negative), only when both timestamps exist
    .withColumn(
        "length_of_stay_days",
        F.when(
            F.col("enc_period_start_ts").isNotNull() & F.col("enc_period_end_ts").isNotNull(),
            F.greatest(F.datediff(F.col("enc_period_end_ts"), F.col("enc_period_start_ts")), F.lit(0))
        ).otherwise(F.lit(None).cast("int"))
    )
    # Week start based on encounter start
    .withColumn("enc_week_start", F.date_trunc("week", F.col("enc_period_start_ts")))
).alias("enc")

# =========================
# Parse Claim JSON fields
# =========================
clm_parsed = (
    clm_bronze
    .withColumn("clm_patient_ref", F.get_json_object(F.col("clm_bronze.raw_json"), "$.patient.reference"))
    .withColumn("clm_provider_ref", F.get_json_object(F.col("clm_bronze.raw_json"), "$.provider.reference"))
    .withColumn("clm_encounter_ref", F.get_json_object(F.col("clm_bronze.raw_json"), "$.item[0].encounter[0].reference"))
    .withColumn("clm_billable_start_raw", F.get_json_object(F.col("clm_bronze.raw_json"), "$.billablePeriod.start"))
    .withColumn("clm_billable_end_raw", F.get_json_object(F.col("clm_bronze.raw_json"), "$.billablePeriod.end"))
    .withColumn("clm_total_value_raw", F.get_json_object(F.col("clm_bronze.raw_json"), "$.total.value"))
    # Parse timestamps per data profile (ISO 8601)
    .withColumn("clm_billable_start_ts", F.coalesce(F.try_to_timestamp(F.col("clm_billable_start_raw"), F.lit("MM/dd/yyyy HH:mm")), F.try_to_timestamp(F.col("clm_billable_start_raw"))))
    .withColumn("clm_billable_end_ts", F.coalesce(F.try_to_timestamp(F.col("clm_billable_end_raw"), F.lit("MM/dd/yyyy HH:mm")), F.try_to_timestamp(F.col("clm_billable_end_raw"))))
    # Cast billed amount safely
    .withColumn("clm_total_billed_amount", F.col("clm_total_value_raw").cast("double"))
    # Derive join keys by stripping prefixes
    .withColumn("clm_patient_id", F.when(F.col("clm_patient_ref").isNotNull(), F.regexp_replace(F.col("clm_patient_ref"), "^.*?/", "")).otherwise(F.lit(None)))
    .withColumn("clm_org_id", F.when(F.col("clm_provider_ref").isNotNull(), F.regexp_replace(F.col("clm_provider_ref"), "^.*?/", "")).otherwise(F.lit(None)))
    .withColumn("clm_encounter_id", F.when(F.col("clm_encounter_ref").isNotNull(), F.regexp_replace(F.col("clm_encounter_ref"), "^.*?/", "")).otherwise(F.lit(None)))
    # Week start based on claim billable start
    .withColumn("clm_week_start", F.date_trunc("week", F.col("clm_billable_start_ts")))
    # Paid amount proxy to avoid all-null column if paid not present; default to billed when null
    .withColumn("clm_total_paid_amount", F.when(F.col("clm_total_value_raw").isNotNull(), F.col("clm_total_value_raw").cast("double")).otherwise(F.lit(0.0)))
).alias("clm")

# =========================
# Parse Organization JSON fields
# =========================
org_parsed = (
    org_bronze
    .withColumn("org_name", F.get_json_object(F.col("org_bronze.raw_json"), "$.name"))
    .withColumn("org_id", F.col("org_bronze.resource_id"))
).alias("org")

# =========================
# Parse Patient JSON fields and filter out test/dummy patients
# =========================
pat_parsed_all = (
    pat_bronze
    .withColumn("pat_id", F.col("pat_bronze.resource_id"))
    .withColumn("pat_name_family", F.get_json_object(F.col("pat_bronze.raw_json"), "$.name[0].family"))
    .withColumn("pat_name_given0", F.get_json_object(F.col("pat_bronze.raw_json"), "$.name[0].given[0]"))
    .withColumn("pat_full_name", F.trim(F.concat_ws(" ", F.col("pat_name_given0"), F.col("pat_name_family"))))
    .withColumn("pat_birth_date_raw", F.get_json_object(F.col("pat_bronze.raw_json"), "$.birthDate"))
    # Parse birthDate per profile: yyyy-MM-dd
    .withColumn("pat_birth_date", F.to_date(F.col("pat_birth_date_raw"), "yyyy-MM-dd"))
).alias("pat_all")

# Exclude test/dummy patients using heuristic on name (case-insensitive)
pat_parsed = (
    pat_parsed_all
    .filter(
        ~(
            F.lower(F.coalesce(F.col("pat_full_name"), F.lit(""))).rlike("(^|\\s)(test|dummy)(\\s|$)")
        )
    )
).alias("pat")

# =========================
# Join Claims to Encounters (only encounters with claims)
# =========================
# Prepare minimal columns for performance and clarity
enc_sel = (
    enc_parsed
    .select(
        F.col("enc.encounter_id"),
        F.col("enc.enc_patient_id"),
        F.col("enc.enc_org_id"),
        F.col("enc.enc_period_start_ts"),
        F.col("enc.enc_period_end_ts"),
        F.col("enc.is_inpatient"),
        F.col("enc.length_of_stay_days"),
        F.col("enc.enc_week_start")
    )
).alias("enc")

clm_sel = (
    clm_parsed
    .select(
        F.col("clm.clm_encounter_id"),
        F.col("clm.clm_patient_id"),
        F.col("clm.clm_org_id"),
        F.col("clm.clm_billable_start_ts"),
        F.col("clm.clm_billable_end_ts"),
        F.col("clm.clm_total_billed_amount"),
        F.col("clm.clm_total_paid_amount"),
        F.col("clm.clm_week_start")
    )
).alias("clm")

# Inner join to satisfy "exclude encounters with no claim"
enc_clm = (
    enc_sel.join(clm_sel, F.col("enc.encounter_id") == F.col("clm.clm_encounter_id"), "inner")
    .select(
        F.col("enc.encounter_id").alias("encounter_id"),
        F.col("enc.enc_patient_id").alias("patient_id_from_enc"),
        F.col("clm.clm_patient_id").alias("patient_id_from_clm"),
        # Resolve patient_id preferring claim, fallback to encounter
        F.coalesce(F.col("clm.clm_patient_id"), F.col("enc.enc_patient_id")).alias("patient_id"),
        F.col("enc.enc_org_id").alias("enc_org_id"),
        F.col("clm.clm_org_id").alias("clm_org_id"),
        F.coalesce(F.col("clm.clm_org_id"), F.col("enc.enc_org_id")).alias("org_id"),
        F.col("enc.enc_period_start_ts").alias("enc_start_ts"),
        F.col("enc.enc_period_end_ts").alias("enc_end_ts"),
        F.col("enc.is_inpatient").alias("is_inpatient"),
        F.col("enc.length_of_stay_days").alias("length_of_stay_days"),
        # Week selection: prefer claim week if available, else encounter week
        F.coalesce(F.col("clm.clm_week_start"), F.col("enc.enc_week_start")).alias("week_start"),
        F.col("clm.clm_total_billed_amount").alias("billed_amount"),
        F.col("clm.clm_total_paid_amount").alias("paid_amount")
    )
).alias("j")

# =========================
# Join to Organization to get facility name
# =========================
j_with_org = (
    enc_clm.join(org_parsed, F.col("j.org_id") == F.col("org.org_id"), "left")
    .select(
        F.col("j.encounter_id"),
        F.col("j.patient_id"),
        F.col("j.org_id").alias("facility_id_resolved"),
        F.col("org.org_name").alias("facility_name_resolved"),
        F.col("j.enc_start_ts"),
        F.col("j.enc_end_ts"),
        F.col("j.is_inpatient"),
        F.col("j.length_of_stay_days"),
        F.col("j.week_start"),
        F.col("j.billed_amount"),
        # Ensure paid_amount is not all-null by defaulting nulls to 0.0
        F.coalesce(F.col("j.paid_amount"), F.lit(0.0)).alias("paid_amount")
    )
).alias("jo")

# =========================
# Filter to patients (exclude test/dummy) and attach patient dimension
# =========================
j_with_patient = (
    j_with_org.join(pat_parsed, F.col("jo.patient_id") == F.col("pat.pat_id"), "inner")
    .select(
        F.col("jo.encounter_id"),
        F.col("jo.patient_id"),
        F.col("jo.facility_id_resolved"),
        F.col("jo.facility_name_resolved"),
        F.col("jo.enc_start_ts"),
        F.col("jo.enc_end_ts"),
        F.col("jo.is_inpatient"),
        F.col("jo.length_of_stay_days"),
        F.col("jo.week_start"),
        F.col("jo.billed_amount"),
        F.col("jo.paid_amount")
    )
).alias("jp")

# =========================
# Compute readmission within 30 days per patient (based on inpatient discharges)
# =========================
# For readmissions, we consider any encounter for the same patient starting within 30 days after an inpatient discharge
window_by_patient = Window.partitionBy("patient_id").orderBy(F.col("enc_start_ts").asc())

# Identify the previous discharge end timestamp for inpatient encounters
jp_with_prev = (
    j_with_patient
    .withColumn("prev_enc_end_ts", F.lag(F.col("enc_end_ts")).over(window_by_patient))
    .withColumn("prev_is_inpatient", F.lag(F.col("is_inpatient")).over(window_by_patient))
    # Readmission flag: current encounter starts within 30 days of previous inpatient discharge
    .withColumn(
        "is_readmission_30d",
        F.when(
            (F.col("prev_is_inpatient") == 1) &
            F.col("prev_enc_end_ts").isNotNull() &
            F.col("enc_start_ts").isNotNull() &
            (F.datediff(F.col("enc_start_ts"), F.col("prev_enc_end_ts")) <= 30) &
            (F.datediff(F.col("enc_start_ts"), F.col("prev_enc_end_ts")) >= 0),
            F.lit(1)
        ).otherwise(F.lit(0))
    )
).alias("r")

# =========================
# Aggregate to facility per week metrics
# =========================
agg_df = (
    jp_with_prev
    .groupBy(
        F.col("facility_id_resolved").alias("facility_id"),
        F.col("facility_name_resolved").alias("facility_name"),
        F.col("week_start")
    )
    .agg(
        # Encounter count
        F.count(F.lit(1)).alias("encounter_count"),
        # Readmission encounters within 30 days
        F.sum(F.col("is_readmission_30d").cast("long")).alias("readmission_encounters"),
        # Financials
        F.sum(F.col("billed_amount")).alias("total_billed_amount"),
        F.sum(F.col("paid_amount")).alias("total_paid_amount"),
        # Average LOS for inpatient encounters only
        F.avg(F.when(F.col("is_inpatient") == 1, F.col("length_of_stay_days"))).alias("average_length_of_stay")
    )
    # Readmission rate = readmissions / encounters (defensive division)
    .withColumn(
        "readmission_rate",
        F.when(F.col("encounter_count") > 0, F.col("readmission_encounters") / F.col("encounter_count")).otherwise(F.lit(0.0))
    )
    .select(
        F.col("facility_id"),
        F.col("facility_name"),
        F.col("week_start"),
        F.col("encounter_count").cast("long").alias("encounter_count"),
        F.col("readmission_rate").cast("double").alias("readmission_rate"),
        F.col("total_billed_amount").cast("double").alias("total_billed_amount"),
        F.col("total_paid_amount").cast("double").alias("total_paid_amount"),
        F.col("average_length_of_stay").cast("double").alias("average_length_of_stay")
    )
)

# =========================
# Create target schema and write result to Delta table
# =========================
spark.sql("CREATE SCHEMA IF NOT EXISTS agentops.gold")
agg_df.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("agentops.gold.agentops_weekly_facility_report")

# =========================
# Display sample for validation
# =========================
result_df = spark.table("agentops.gold.agentops_weekly_facility_report")
display(result_df.limit(20))