# Databricks notebook source
# Generated by Agent 03A for DBXCOE-29 | plan 36033837cdfe8efb | tests a63aee0d909afd37 | attempt 6 | 2026-10-03T07:00:04.748086+00:00
# Plan approved by system:auto_approve (auto_approved)

# COMMAND ----------

from pyspark.sql import functions as F, DataFrame
from pyspark.sql import Window
dbutils.widgets.text("target_catalog", "agentops")
dbutils.widgets.text("target_schema", "gold")
dbutils.widgets.text("run_mode", "run")
TARGET_CATALOG = dbutils.widgets.get("target_catalog")
TARGET_SCHEMA = dbutils.widgets.get("target_schema")
RUN_MODE = dbutils.widgets.get("run_mode")

# COMMAND ----------

def build(spark, sources: dict) -> dict:
    """
    Build ED Utilization Monthly report from bronze sources.
    
    Returns dict with key 'ed_utilization_monthly' containing aggregated metrics
    per facility per month for ED encounters with linked claims, excluding test patients.
    
    Key business rules:
    - Filter to ED encounters only (class = EMER)
    - Exclude encounters without linked claims
    - Exclude test/dummy patients
    - Aggregate by facility_id, facility_name, month_start
    - Multiple claims per encounter are summed first, then averaged across encounters
    - Conditions are counted per encounter, then averaged across encounters
    - Top condition is the most frequent condition code per facility-month
    - Admits from ED: inpatient encounters starting within 24 hours of ED end
    """
    
    encounter = sources["encounter"]
    claim = sources["claim"]
    patient = sources["patient"]
    organization = sources["organization"]
    condition = sources["condition"]
    
    # ===== STEP 1: Parse and filter Encounter data for ED visits =====
    # Extract encounter class, subject (patient), service provider (facility), and period
    enc = (
        encounter
        .withColumn("enc_class_code", F.get_json_object(F.col("raw_json"), "$.class.code"))
        .withColumn("enc_subject_ref", F.get_json_object(F.col("raw_json"), "$.subject.reference"))
        .withColumn("enc_service_provider_ref", F.get_json_object(F.col("raw_json"), "$.serviceProvider.reference"))
        .withColumn("enc_period_start_raw", F.get_json_object(F.col("raw_json"), "$.period.start"))
        .withColumn("enc_period_end_raw", F.get_json_object(F.col("raw_json"), "$.period.end"))
        # Parse ISO 8601 timestamps using try_to_timestamp (ANSI mode safe)
        .withColumn("enc_period_start", F.expr("try_to_timestamp(enc_period_start_raw)"))
        .withColumn("enc_period_end", F.expr("try_to_timestamp(enc_period_end_raw)"))
        # Extract IDs by stripping reference prefixes
        .withColumn("patient_id", F.regexp_replace(F.col("enc_subject_ref"), "^.*?/", ""))
        .withColumn("facility_id", F.regexp_replace(F.col("enc_service_provider_ref"), "^.*?/", ""))
        # Derive month_start from encounter start (first day of month)
        .withColumn("month_start", F.trunc(F.col("enc_period_start"), "month").cast("date"))
        # Filter to ED encounters only (class code = EMER)
        .filter(F.upper(F.col("enc_class_code")) == "EMER")
        .select(
            F.col("resource_id").alias("encounter_id"),
            F.col("patient_id"),
            F.col("facility_id"),
            F.col("month_start"),
            F.col("enc_period_start"),
            F.col("enc_period_end")
        )
    )
    
    # ===== STEP 2: Parse and link Claims =====
    # Extract claim encounter reference, patient reference, and total amount
    clm = (
        claim
        .withColumn("clm_patient_ref", F.get_json_object(F.col("raw_json"), "$.patient.reference"))
        .withColumn("clm_provider_ref", F.get_json_object(F.col("raw_json"), "$.provider.reference"))
        .withColumn("clm_encounter_ref", F.get_json_object(F.col("raw_json"), "$.item[0].encounter[0].reference"))
        .withColumn("clm_total_value", F.get_json_object(F.col("raw_json"), "$.total.value"))
        # Cast claim amount to decimal(18,2) for money using try_cast (ANSI mode safe)
        .withColumn("claim_amount", F.expr("try_cast(clm_total_value AS DECIMAL(18,2))"))
        # Extract IDs by stripping reference prefixes
        .withColumn("clm_patient_id", F.regexp_replace(F.col("clm_patient_ref"), "^.*?/", ""))
        .withColumn("clm_encounter_id", F.regexp_replace(F.col("clm_encounter_ref"), "^.*?/", ""))
        .select(
            F.col("resource_id").alias("claim_id"),
            F.col("clm_encounter_id").alias("encounter_id"),
            F.col("clm_patient_id").alias("patient_id"),
            F.col("claim_amount")
        )
    )
    
    # ===== STEP 3: Parse Patient data and identify test/dummy records =====
    # Extract patient name and MRN to detect test/dummy records
    pat = (
        patient
        .withColumn("pat_name_raw", F.get_json_object(F.col("raw_json"), "$.name[0].family"))
        .withColumn("pat_mrn_raw", F.get_json_object(F.col("raw_json"), "$.identifier[0].value"))
        # Mark as test if name or MRN contains 'test' or 'dummy' (case-insensitive)
        .withColumn("is_test_patient", 
            F.when(
                (F.lower(F.col("pat_name_raw")).contains("test")) |
                (F.lower(F.col("pat_name_raw")).contains("dummy")) |
                (F.lower(F.col("pat_mrn_raw")).contains("test")) |
                (F.lower(F.col("pat_mrn_raw")).contains("dummy")),
                True
            ).otherwise(False)
        )
        .select(
            F.col("resource_id").alias("patient_id"),
            F.col("is_test_patient")
        )
    )
    
    # ===== STEP 4: Parse Organization data for facility names =====
    # Extract organization name for facility_name dimension
    org = (
        organization
        .withColumn("org_name", F.get_json_object(F.col("raw_json"), "$.name"))
        .select(
            F.col("resource_id").alias("facility_id"),
            F.col("org_name").alias("facility_name")
        )
    )
    
    # ===== STEP 5: Parse Condition data =====
    # Extract condition code and link to encounter
    cond = (
        condition
        .withColumn("cond_code", F.get_json_object(F.col("raw_json"), "$.code.coding[0].code"))
        .withColumn("cond_encounter_ref", F.get_json_object(F.col("raw_json"), "$.encounter.reference"))
        .withColumn("cond_encounter_id", F.regexp_replace(F.col("cond_encounter_ref"), "^.*?/", ""))
        .select(
            F.col("cond_encounter_id").alias("encounter_id"),
            F.col("cond_code").alias("condition_code")
        )
    )
    
    # ===== STEP 6: Join Encounter + Claim (link encounters to claims) =====
    # Filter: only encounters with linked claims (inner join)
    enc_with_claim = (
        enc.alias("enc_left")
        .join(clm.alias("clm_right"), on=F.col("enc_left.encounter_id") == F.col("clm_right.encounter_id"), how="inner")
        .select(
            F.col("enc_left.encounter_id"),
            F.col("enc_left.patient_id"),
            F.col("enc_left.facility_id"),
            F.col("enc_left.month_start"),
            F.col("enc_left.enc_period_start"),
            F.col("enc_left.enc_period_end"),
            F.col("clm_right.claim_id"),
            F.col("clm_right.claim_amount")
        )
    )
    
    # ===== STEP 7: Filter out test/dummy patients =====
    # Exclude encounters for test/dummy patients
    enc_with_claim_valid = (
        enc_with_claim.alias("enc_claim")
        .join(pat.alias("pat_right"), on=F.col("enc_claim.patient_id") == F.col("pat_right.patient_id"), how="left")
        .filter(F.col("pat_right.is_test_patient").isNull() | (F.col("pat_right.is_test_patient") == False))
        .select(
            F.col("enc_claim.encounter_id"),
            F.col("enc_claim.patient_id"),
            F.col("enc_claim.facility_id"),
            F.col("enc_claim.month_start"),
            F.col("enc_claim.enc_period_start"),
            F.col("enc_claim.enc_period_end"),
            F.col("enc_claim.claim_id"),
            F.col("enc_claim.claim_amount")
        )
    )
    
    # ===== STEP 8: Add facility name =====
    # Join with organization to get facility_name
    enc_with_claim_valid = (
        enc_with_claim_valid.alias("enc_valid")
        .join(org.alias("org_right"), on=F.col("enc_valid.facility_id") == F.col("org_right.facility_id"), how="left")
        .select(
            F.col("enc_valid.encounter_id"),
            F.col("enc_valid.patient_id"),
            F.col("enc_valid.facility_id"),
            F.col("enc_valid.month_start"),
            F.col("enc_valid.enc_period_start"),
            F.col("enc_valid.enc_period_end"),
            F.col("enc_valid.claim_id"),
            F.col("enc_valid.claim_amount"),
            F.col("org_right.facility_name")
        )
    )
    
    # ===== STEP 9: Aggregate claims per encounter BEFORE joining conditions =====
    # Sum multiple claims per encounter; this produces one row per encounter with summed claim amount
    claims_per_enc = (
        enc_with_claim_valid
        .groupBy("encounter_id", "patient_id", "facility_id", "month_start", "facility_name", "enc_period_start", "enc_period_end")
        .agg(
            F.sum("claim_amount").alias("encounter_total_billed")
        )
    )
    
    # ===== STEP 10: Join with conditions per encounter =====
    # Left join to include encounters with no conditions
    enc_with_conditions = (
        claims_per_enc.alias("enc_clm")
        .join(cond.alias("cond_right"), on=F.col("enc_clm.encounter_id") == F.col("cond_right.encounter_id"), how="left")
        .select(
            F.col("enc_clm.encounter_id"),
            F.col("enc_clm.patient_id"),
            F.col("enc_clm.facility_id"),
            F.col("enc_clm.month_start"),
            F.col("enc_clm.enc_period_start"),
            F.col("enc_clm.enc_period_end"),
            F.col("enc_clm.encounter_total_billed"),
            F.col("enc_clm.facility_name"),
            F.col("cond_right.condition_code")
        )
    )
    
    # ===== STEP 11: Identify ED to Inpatient admissions within 24 hours =====
    # Parse all encounters to find inpatient admissions
    all_enc = (
        encounter
        .withColumn("enc_class_code", F.get_json_object(F.col("raw_json"), "$.class.code"))
        .withColumn("enc_subject_ref", F.get_json_object(F.col("raw_json"), "$.subject.reference"))
        .withColumn("enc_period_start_raw", F.get_json_object(F.col("raw_json"), "$.period.start"))
        .withColumn("enc_period_start", F.expr("try_to_timestamp(enc_period_start_raw)"))
        .withColumn("patient_id", F.regexp_replace(F.col("enc_subject_ref"), "^.*?/", ""))
        # Filter to inpatient encounters only
        .filter(F.upper(F.col("enc_class_code")) == "IMP")
        .select(
            F.col("resource_id").alias("imp_encounter_id"),
            F.col("patient_id"),
            F.col("enc_period_start").alias("imp_start")
        )
    )
    
    # Get distinct ED encounters for join
    ed_encounters = (
        enc_with_conditions
        .select(
            F.col("encounter_id").alias("ed_encounter_id"),
            F.col("patient_id"),
            F.col("enc_period_end")
        )
        .distinct()
    )
    
    # Join ED to inpatient: same patient, IMP starts within 24 hours of ED end
    ed_to_imp = (
        ed_encounters.alias("ed_enc")
        .join(all_enc.alias("imp_enc"), on=F.col("ed_enc.patient_id") == F.col("imp_enc.patient_id"), how="left")
        .withColumn("hours_to_admission", 
            F.expr("try_divide(cast(unix_timestamp(imp_start) - unix_timestamp(enc_period_end) as double), 3600.0)")
        )
        # Filter: admission must occur within 24 hours after ED end (0 to 24 hours)
        .filter((F.col("hours_to_admission").isNotNull()) & (F.col("hours_to_admission") >= 0) & (F.col("hours_to_admission") <= 24))
        .select(F.col("ed_enc.ed_encounter_id").alias("encounter_id"))
        .distinct()
    )
    
    # Mark admits_from_ed flag using left join
    enc_with_conditions = (
        enc_with_conditions.alias("enc_main")
        .join(ed_to_imp.alias("admits"), on=F.col("enc_main.encounter_id") == F.col("admits.encounter_id"), how="left")
        .withColumn("is_admit_from_ed", F.when(F.col("admits.encounter_id").isNotNull(), F.lit(1)).otherwise(F.lit(0)))
        .select(
            F.col("enc_main.encounter_id"),
            F.col("enc_main.patient_id"),
            F.col("enc_main.facility_id"),
            F.col("enc_main.month_start"),
            F.col("enc_main.enc_period_start"),
            F.col("enc_main.enc_period_end"),
            F.col("enc_main.encounter_total_billed"),
            F.col("enc_main.facility_name"),
            F.col("enc_main.condition_code"),
            F.col("is_admit_from_ed")
        )
    )
    
    # ===== STEP 12: Count conditions per encounter =====
    # Count non-null condition codes per encounter
    conditions_per_enc = (
        enc_with_conditions
        .groupBy("encounter_id")
        .agg(
            F.count(F.when(F.col("condition_code").isNotNull(), F.lit(1))).alias("condition_count")
        )
    )
    
    # Rejoin conditions count
    enc_with_conditions = (
        enc_with_conditions.alias("enc_f1")
        .join(conditions_per_enc.alias("cond_cnt"), on=F.col("enc_f1.encounter_id") == F.col("cond_cnt.encounter_id"), how="left")
        .withColumn("condition_count", F.coalesce(F.col("cond_cnt.condition_count"), F.lit(0)))
        .select(
            F.col("enc_f1.encounter_id"),
            F.col("enc_f1.patient_id"),
            F.col("enc_f1.facility_id"),
            F.col("enc_f1.month_start"),
            F.col("enc_f1.facility_name"),
            F.col("enc_f1.encounter_total_billed"),
            F.col("enc_f1.condition_code"),
            F.col("enc_f1.is_admit_from_ed"),
            F.col("condition_count")
        )
    )
    
    # ===== STEP 13: Find top condition per facility-month =====
    # Rank conditions by frequency within each facility-month
    # Only count each encounter once per condition (use distinct)
    top_conditions = (
        enc_with_conditions
        .filter(F.col("condition_code").isNotNull())
        .select("facility_id", "month_start", "encounter_id", "condition_code")
        .distinct()
        .groupBy("facility_id", "month_start", "condition_code")
        .agg(F.count("encounter_id").alias("condition_encounter_count"))
        .withColumn("rank", F.row_number().over(
            Window.partitionBy("facility_id", "month_start").orderBy(F.desc("condition_encounter_count"))
        ))
        # Select top condition (rank = 1)
        .filter(F.col("rank") == 1)
        .select(
            F.col("facility_id"),
            F.col("month_start"),
            F.col("condition_code").alias("top_condition"),
            F.col("condition_encounter_count").alias("top_condition_count")
        )
    )
    
    # ===== STEP 14: Final aggregation by facility-month =====
    # Aggregate ED metrics per facility per month
    # Use distinct on encounter_id to ensure one row per encounter
    result = (
        enc_with_conditions
        .select(
            "facility_id",
            "facility_name",
            "month_start",
            "encounter_id",
            "patient_id",
            "encounter_total_billed",
            "is_admit_from_ed",
            "condition_count"
        )
        .distinct()
        .groupBy("facility_id", "facility_name", "month_start")
        .agg(
            # ed_visit_count: total number of distinct ED encounters
            F.countDistinct("encounter_id").alias("ed_visit_count"),
            # unique_patients: distinct count of patients in ED encounters
            F.countDistinct("patient_id").alias("unique_patients"),
            # avg_claim_amount: average of encounter_total_billed (already summed per encounter)
            F.avg("encounter_total_billed").alias("avg_claim_amount"),
            # total_billed: sum of encounter_total_billed across all encounters
            F.sum("encounter_total_billed").alias("total_billed"),
            # admits_from_ed: count of ED visits converted to inpatient within 24h
            F.sum("is_admit_from_ed").alias("admits_from_ed"),
            # avg_conditions_per_visit: average number of conditions per ED encounter
            F.avg("condition_count").alias("avg_conditions_per_visit")
        )
    )
    
    # ===== STEP 15: Join with top condition =====
    # Add top_condition and top_condition_count dimensions
    result = (
        result.alias("res")
        .join(top_conditions.alias("top_cond"), 
            on=(F.col("res.facility_id") == F.col("top_cond.facility_id")) & 
               (F.col("res.month_start") == F.col("top_cond.month_start")), 
            how="left")
        .select(
            F.col("res.facility_id"),
            F.col("res.facility_name"),
            F.col("res.month_start"),
            F.col("top_cond.top_condition"),
            F.col("res.ed_visit_count"),
            F.col("res.unique_patients"),
            F.col("res.avg_claim_amount"),
            F.col("res.total_billed"),
            F.col("res.admits_from_ed"),
            F.col("res.avg_conditions_per_visit"),
            F.col("top_cond.top_condition_count")
        )
    )
    
    # ===== STEP 16: Cast and round numeric columns =====
    # Format output with correct data types and precision
    result = (
        result
        .withColumn("avg_claim_amount", F.round(F.col("avg_claim_amount"), 2).cast("DECIMAL(18,2)"))
        .withColumn("total_billed", F.round(F.col("total_billed"), 2).cast("DECIMAL(18,2)"))
        .withColumn("avg_conditions_per_visit", F.round(F.col("avg_conditions_per_visit"), 2))
        .withColumn("admits_from_ed", F.col("admits_from_ed").cast("long"))
        .withColumn("ed_visit_count", F.col("ed_visit_count").cast("long"))
        .withColumn("unique_patients", F.col("unique_patients").cast("long"))
        .withColumn("top_condition_count", F.coalesce(F.col("top_condition_count"), F.lit(0)).cast("long"))
        .select(
            "facility_id",
            "facility_name",
            "month_start",
            "top_condition",
            "ed_visit_count",
            "unique_patients",
            "avg_claim_amount",
            "total_billed",
            "admits_from_ed",
            "avg_conditions_per_visit",
            "top_condition_count"
        )
    )
    
    return {"ed_utilization_monthly": result}

# COMMAND ----------

def load_sources(spark) -> dict:
    """Load all bronze source tables."""
    return {
        "encounter": spark.table("agentops.bronze.encounter"),
        "claim": spark.table("agentops.bronze.claim"),
        "patient": spark.table("agentops.bronze.patient"),
        "organization": spark.table("agentops.bronze.organization"),
        "condition": spark.table("agentops.bronze.condition"),
    }

# COMMAND ----------

if RUN_MODE == "run" and not globals().get("AGENTOPS_LIBRARY_MODE", False):
    outputs = build(spark, load_sources(spark))
    
    spark.sql(f"CREATE SCHEMA IF NOT EXISTS {TARGET_CATALOG}.{TARGET_SCHEMA}")
    
    for table_name, df in outputs.items():
        target_table = f"{TARGET_CATALOG}.{TARGET_SCHEMA}.{table_name}"
        df.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(target_table)
        print(f"✓ Wrote {target_table}: {df.count()} rows")