# Databricks notebook source
# Auto-generated by Agent 03A (Coding Agent)
# Request: DBXCOE-29 | Plan: a95fa17a6d787c64 | Approved: auto_approved (system:auto_approve)
# Report: Emergency Department Utilization & Cost Report | Target: agentops.gold.ed_utilization_monthly
# Generated: 2026-10-01T13:29:20.116634+00:00 | Recommendation: new_pipeline
# ---------------------------------------------------------------

from pyspark.sql import functions as F
from pyspark.sql import Window

# =========================================
# Load bronze source tables (aliased)
# =========================================
enc_bronze = spark.table("agentops.bronze.encounter").alias("enc_bronze")
clm_bronze = spark.table("agentops.bronze.claim").alias("clm_bronze")
pat_bronze = spark.table("agentops.bronze.patient").alias("pat_bronze")
org_bronze = spark.table("agentops.bronze.organization").alias("org_bronze")
cond_bronze = spark.table("agentops.bronze.condition").alias("cond_bronze")

# =========================================
# Parse Encounter fields needed for ED logic and facility linkage
# - Extract encounter id, class.code, subject (patient), serviceProvider (facility)
# - Parse period.start and period.end timestamps (ISO 8601 per profile)
# - Derive month_start as first day of month of period.start (per schema_recommendation; open question noted)
# =========================================
enc_parsed = (
    enc_bronze
    .withColumn("enc_id", F.get_json_object(F.col("enc_bronze.raw_json"), "$.id"))
    .withColumn("enc_class", F.get_json_object(F.col("enc_bronze.raw_json"), "$.class.code"))
    .withColumn("enc_subject_ref", F.get_json_object(F.col("enc_bronze.raw_json"), "$.subject.reference"))
    .withColumn("enc_patient_id", F.regexp_replace(F.col("enc_subject_ref"), "^.*?/", ""))
    .withColumn("enc_service_provider_ref", F.get_json_object(F.col("enc_bronze.raw_json"), "$.serviceProvider.reference"))
    .withColumn("facility_id_raw", F.regexp_replace(F.col("enc_service_provider_ref"), "^.*?/", ""))
    .withColumn("period_start_str", F.get_json_object(F.col("enc_bronze.raw_json"), "$.period.start"))
    .withColumn("period_end_str", F.get_json_object(F.col("enc_bronze.raw_json"), "$.period.end"))
    .withColumn("period_start_ts", F.coalesce(F.try_to_timestamp(F.col("period_start_str"), F.lit("MM/dd/yyyy HH:mm")), F.try_to_timestamp(F.col("period_start_str"))))
    .withColumn("period_end_ts", F.coalesce(F.try_to_timestamp(F.col("period_end_str"), F.lit("MM/dd/yyyy HH:mm")), F.try_to_timestamp(F.col("period_end_str"))))
    # Defensive: If period.start is null, we cannot derive month; drop such records later when grouping
    .withColumn("month_start", F.trunc(F.col("period_start_ts"), "month"))
    .select(
        F.col("enc_id"),
        F.col("enc_class"),
        F.col("enc_patient_id"),
        F.col("facility_id_raw").alias("facility_id"),
        F.col("period_start_ts"),
        F.col("period_end_ts"),
        F.col("month_start")
    )
    .alias("enc")
)

# =========================================
# Filter to ED encounters (class = 'EMER')
# =========================================
ed_enc = (
    enc_parsed
    .filter(F.col("enc.enc_class") == F.lit("EMER"))
    .filter(F.col("enc.month_start").isNotNull())  # ensure month derivation available
    .alias("enc")
)

# =========================================
# Parse Claim fields and link to Encounter
# - Extract claim id, patient, provider, total.value, billablePeriod timestamps
# - Extract encounter reference from item[0].encounter[0].reference (per profile)
# - Link key: claim encounter ref (Encounter/<id>) -> encounter.id
# Note: We will pre-aggregate multiple claims per encounter to an encounter-level total for averages/sums
# =========================================
clm_parsed = (
    clm_bronze
    .withColumn("claim_id", F.get_json_object(F.col("clm_bronze.raw_json"), "$.id"))
    .withColumn("claim_patient_ref", F.get_json_object(F.col("clm_bronze.raw_json"), "$.patient.reference"))
    .withColumn("claim_patient_id", F.regexp_replace(F.col("claim_patient_ref"), "^.*?/", ""))
    .withColumn("claim_provider_ref", F.get_json_object(F.col("clm_bronze.raw_json"), "$.provider.reference"))
    .withColumn("claim_provider_id", F.regexp_replace(F.col("claim_provider_ref"), "^.*?/", ""))
    .withColumn("claim_enc_ref", F.get_json_object(F.col("clm_bronze.raw_json"), "$.item[0].encounter[0].reference"))
    .withColumn("claim_enc_id", F.regexp_replace(F.col("claim_enc_ref"), "^.*?/", ""))
    .withColumn("bill_start_str", F.get_json_object(F.col("clm_bronze.raw_json"), "$.billablePeriod.start"))
    .withColumn("bill_end_str", F.get_json_object(F.col("clm_bronze.raw_json"), "$.billablePeriod.end"))
    .withColumn("bill_start_ts", F.coalesce(F.try_to_timestamp(F.col("bill_start_str"), F.lit("MM/dd/yyyy HH:mm")), F.try_to_timestamp(F.col("bill_start_str"))))
    .withColumn("bill_end_ts", F.coalesce(F.try_to_timestamp(F.col("bill_end_str"), F.lit("MM/dd/yyyy HH:mm")), F.try_to_timestamp(F.col("bill_end_str"))))
    .withColumn("claim_total_value_str", F.get_json_object(F.col("clm_bronze.raw_json"), "$.total.value"))
    # Defensive cast: total.value can be string/number; cast to double safely
    .withColumn("claim_total_value", F.when(F.col("claim_total_value_str").isNotNull(), F.col("claim_total_value_str").cast("double")).otherwise(F.lit(None).cast("double")))
    .select(
        F.col("claim_id"),
        F.col("claim_patient_id"),
        F.col("claim_provider_id"),
        F.col("claim_enc_id"),
        F.col("claim_total_value"),
        F.col("bill_start_ts"),
        F.col("bill_end_ts")
    )
    .alias("clm")
)

# =========================================
# Pre-aggregate claim totals per encounter
# - Sum multiple claims per encounter to one encounter_total
# - Also compute count of claims per encounter (for debugging/analysis if needed)
# =========================================
clm_per_enc = (
    clm_parsed
    .filter(F.col("clm.claim_enc_id").isNotNull())
    .groupBy(F.col("clm.claim_enc_id").alias("enc_id"))
    .agg(
        F.sum(F.coalesce(F.col("clm.claim_total_value"), F.lit(0.0))).alias("encounter_claim_total"),
        F.count(F.lit(1)).alias("claims_linked_count")
    )
    .alias("cpe")
)

# =========================================
# Link ED encounters with claims to enforce "exclude encounters without linked claims"
# - Inner join ensures only encounters with at least one linked claim remain
# =========================================
ed_enc_with_claims = (
    ed_enc.join(clm_per_enc, F.col("enc.enc_id") == F.col("cpe.enc_id"), "inner")
    .select(
        F.col("enc.enc_id"),
        F.col("enc.enc_patient_id"),
        F.col("enc.facility_id"),
        F.col("enc.period_start_ts"),
        F.col("enc.period_end_ts"),
        F.col("enc.month_start"),
        F.col("cpe.encounter_claim_total"),
        F.col("cpe.claims_linked_count")
    )
    .alias("edc")
)

# =========================================
# Parse Organization to get facility name
# =========================================
org_parsed = (
    org_bronze
    .withColumn("org_id", F.get_json_object(F.col("org_bronze.raw_json"), "$.id"))
    .withColumn("org_name", F.get_json_object(F.col("org_bronze.raw_json"), "$.name"))
    .select(F.col("org_id"), F.col("org_name"))
    .alias("org")
)

# =========================================
# Join facility name; coalesce name to facility_id when missing
# =========================================
ed_enc_enriched = (
    ed_enc_with_claims
    .join(org_parsed, F.col("edc.facility_id") == F.col("org.org_id"), "left")
    .withColumn("facility_name", F.coalesce(F.col("org.org_name"), F.col("edc.facility_id")))
    .select(
        F.col("edc.enc_id"),
        F.col("edc.enc_patient_id"),
        F.col("edc.facility_id"),
        F.col("facility_name"),
        F.col("edc.period_start_ts"),
        F.col("edc.period_end_ts"),
        F.col("edc.month_start"),
        F.col("edc.encounter_claim_total"),
        F.col("edc.claims_linked_count")
    )
    .alias("ede")
)

# =========================================
# Patient-based exclusions: Exclude test/dummy patients
# Open question; no definitive rule provided in profile.
# Implement a conservative heuristic: exclude patients with active=false OR
# names that contain 'test'/'dummy' (case-insensitive), if name present.
# If patient record missing, retain (cannot assert test), but we only have linked claims so likely present.
# =========================================
pat_parsed = (
    pat_bronze
    .withColumn("pat_id", F.get_json_object(F.col("pat_bronze.raw_json"), "$.id"))
    .withColumn("pat_active_str", F.get_json_object(F.col("pat_bronze.raw_json"), "$.active"))
    .withColumn("pat_active", F.when(F.lower(F.col("pat_active_str")) == F.lit("true"), F.lit(True))
                .when(F.lower(F.col("pat_active_str")) == F.lit("false"), F.lit(False))
                .otherwise(F.lit(True)))  # default to active if missing
    .withColumn("family_name", F.get_json_object(F.col("pat_bronze.raw_json"), "$.name[0].family"))
    .withColumn("given0_name", F.get_json_object(F.col("pat_bronze.raw_json"), "$.name[0].given[0]"))
    .withColumn("full_name", F.concat_ws(" ", F.col("given0_name"), F.col("family_name")))
    .withColumn("is_test_name",
                F.when(F.col("full_name").isNotNull(),
                       F.lower(F.col("full_name")).rlike("(^|\\s)(test|dummy|demo|synthetic)($|\\s)"))
                .otherwise(F.lit(False)))
    .select(
        F.col("pat_id"),
        F.col("pat_active"),
        F.col("is_test_name")
    )
    .alias("pat")
)

ed_enc_enriched_pat = (
    ed_enc_enriched
    .join(pat_parsed, F.col("ede.enc_patient_id") == F.col("pat.pat_id"), "left")
    .filter(F.coalesce(F.col("pat.pat_active"), F.lit(True)) == F.lit(True))  # keep only active or unknown treated as active
    .filter(F.coalesce(F.col("pat.is_test_name"), F.lit(False)) == F.lit(False))  # exclude test/dummy names
    .select(
        F.col("ede.enc_id"),
        F.col("ede.enc_patient_id"),
        F.col("ede.facility_id"),
        F.col("ede.facility_name"),
        F.col("ede.period_start_ts"),
        F.col("ede.period_end_ts"),
        F.col("ede.month_start"),
        F.col("ede.encounter_claim_total"),
        F.col("ede.claims_linked_count")
    )
    .alias("ede")
)

# =========================================
# Conditions linkage to encounters
# - Extract condition code (code.coding[0].code) and encounter reference
# - Compute count of conditions per encounter and set for mode computation
# =========================================
cond_parsed = (
    cond_bronze
    .withColumn("cond_id", F.get_json_object(F.col("cond_bronze.raw_json"), "$.id"))
    .withColumn("cond_code", F.get_json_object(F.col("cond_bronze.raw_json"), "$.code.coding[0].code"))
    .withColumn("cond_enc_ref", F.get_json_object(F.col("cond_bronze.raw_json"), "$.encounter.reference"))
    .withColumn("cond_enc_id", F.regexp_replace(F.col("cond_enc_ref"), "^.*?/", ""))
    .select(F.col("cond_id"), F.col("cond_code"), F.col("cond_enc_id"))
    .alias("cond")
)

# Count conditions per encounter
cond_counts_per_enc = (
    cond_parsed
    .groupBy(F.col("cond.cond_enc_id").alias("enc_id"))
    .agg(F.count(F.col("cond.cond_id")).alias("cond_count_enc"))
    .alias("ccte")
)

# For top condition per facility-month, we will join detail later to aggregate frequency
# =========================================
# Compute admits_from_ed:
# - Identify for each ED encounter if the same patient has a subsequent inpatient (IMP) encounter
#   starting within 24 hours after the ED encounter start.
# - Approach: self-join encounter table (not just ED subset) to find IMP within 24h
# =========================================
# Prepare all encounters minimal set for admit detection
all_enc_min = (
    enc_parsed
    .select(
        F.col("enc_id").alias("enc2_id"),
        F.col("enc_patient_id").alias("enc2_patient_id"),
        F.col("enc_class").alias("enc2_class"),
        F.col("period_start_ts").alias("enc2_start_ts"),
        F.col("facility_id").alias("enc2_facility_id")
    )
    .alias("aenc")
)

# Join ED encounters to IMP encounters for same patient within 24 hours after ED start
ed_to_imp = (
    ed_enc_enriched_pat.alias("ed")
    .join(
        all_enc_min.alias("imp"),
        (
            (F.col("ed.enc_patient_id") == F.col("imp.enc2_patient_id")) &
            (F.col("imp.enc2_class") == F.lit("IMP")) &
            (F.col("imp.enc2_start_ts").isNotNull()) &
            (F.col("ed.period_start_ts").isNotNull()) &
            (F.col("imp.enc2_start_ts") >= F.col("ed.period_start_ts")) &
            (F.col("imp.enc2_start_ts") <= F.col("ed.period_start_ts") + F.expr("INTERVAL 24 HOURS"))
        ),
        "left"
    )
    .withColumn("imp_exists", F.when(F.col("imp.enc2_id").isNotNull(), F.lit(1)).otherwise(F.lit(0)))
    # In case multiple IMP encounters qualify, reduce to one flag per ED encounter
    .groupBy(
        F.col("ed.enc_id"),
        F.col("ed.facility_id"),
        F.col("ed.facility_name"),
        F.col("ed.month_start"),
        F.col("ed.enc_patient_id"),
        F.col("ed.encounter_claim_total"),
        F.col("ed.claims_linked_count"),
        F.col("ed.period_start_ts"),
        F.col("ed.period_end_ts")
    )
    .agg(F.max(F.col("imp_exists")).alias("admit_from_ed_flag"))
    .alias("edi")
)

# =========================================
# Join condition counts to ED encounters (for avg_conditions_per_visit)
# =========================================
edi_with_cond_counts = (
    ed_to_imp.alias("edi")
    .join(cond_counts_per_enc.alias("cc"), F.col("edi.enc_id") == F.col("cc.enc_id"), "left")
    .withColumn("cond_count_enc", F.coalesce(F.col("cc.cond_count_enc"), F.lit(0)))
    .select(
        F.col("edi.enc_id"),
        F.col("edi.facility_id"),
        F.col("edi.facility_name"),
        F.col("edi.month_start"),
        F.col("edi.enc_patient_id"),
        F.col("edi.encounter_claim_total"),
        F.col("edi.claims_linked_count"),
        F.col("edi.admit_from_ed_flag"),
        F.col("edi.period_start_ts"),
        F.col("edi.period_end_ts"),
        F.col("cond_count_enc")
    )
    .alias("edall")
)

# =========================================
# Compute top_condition per facility-month:
# - Join ED encounters with condition details and aggregate frequency of codes.
# - Break ties deterministically by choosing smallest code lexicographically.
# =========================================
ed_condition_detail = (
    edi_with_cond_counts.alias("edm")
    .join(cond_parsed.alias("cd"), F.col("edm.enc_id") == F.col("cd.cond_enc_id"), "left")
    .select(
        F.col("edm.facility_id"),
        F.col("edm.facility_name"),
        F.col("edm.month_start"),
        F.col("cd.cond_code")
    )
    .alias("ecd")
)

top_condition_per_fac_month = (
    ed_condition_detail
    .groupBy(F.col("ecd.facility_id"), F.col("ecd.facility_name"), F.col("ecd.month_start"), F.col("ecd.cond_code"))
    .agg(F.count(F.lit(1)).alias("cond_freq"))
    .withColumn("cond_code_filled", F.coalesce(F.col("ecd.cond_code"), F.lit("UNKNOWN")))
    .select(
        F.col("ecd.facility_id").alias("facility_id"),
        F.col("ecd.facility_name").alias("facility_name"),
        F.col("ecd.month_start").alias("month_start"),
        F.col("cond_code_filled").alias("cond_code"),
        F.col("cond_freq")
    )
    .withColumn("rn", F.row_number().over(
        Window.partitionBy("facility_id", "facility_name", "month_start")
        .orderBy(F.col("cond_freq").desc(), F.col("cond_code").asc())
    ))
    .filter(F.col("rn") == F.lit(1))
    .select(
        F.col("facility_id"),
        F.col("facility_name"),
        F.col("month_start"),
        F.when(F.col("cond_code") == F.lit("UNKNOWN"), F.lit(None)).otherwise(F.col("cond_code")).alias("top_condition")
    )
    .alias("topc")
)

# =========================================
# Aggregate metrics per facility-month
# Metrics:
# - ed_visit_count: number of ED encounters (after filters and with linked claims)
# - unique_patients: distinct count of patients
# - avg_claim_amount: average of encounter_claim_total across ED encounters (encounters w/ claims already)
# - total_billed: sum of encounter_claim_total
# - admits_from_ed: sum of admit_from_ed_flag
# - avg_conditions_per_visit: average of cond_count_enc
# - top_condition: from computed mode table
# =========================================
metrics_base = (
    edi_with_cond_counts
    .groupBy(F.col("facility_id"), F.col("facility_name"), F.col("month_start"))
    .agg(
        F.count(F.lit(1)).alias("ed_visit_count"),
        F.countDistinct(F.col("enc_patient_id")).alias("unique_patients"),
        F.avg(F.col("encounter_claim_total")).alias("avg_claim_amount"),
        F.sum(F.col("encounter_claim_total")).alias("total_billed"),
        F.sum(F.col("admit_from_ed_flag")).alias("admits_from_ed"),
        F.avg(F.col("cond_count_enc").cast("double")).alias("avg_conditions_per_visit")
    )
    .alias("mb")
)

# Join top_condition
final_df = (
    metrics_base.alias("mb")
    .join(
        top_condition_per_fac_month.alias("tc"),
        (F.col("mb.facility_id") == F.col("tc.facility_id")) &
        (F.col("mb.facility_name") == F.col("tc.facility_name")) &
        (F.col("mb.month_start") == F.col("tc.month_start")),
        "left"
    )
    .select(
        F.col("mb.facility_id"),
        F.col("mb.facility_name"),
        F.col("mb.month_start"),
        F.col("mb.ed_visit_count"),
        F.col("mb.unique_patients"),
        F.col("mb.avg_claim_amount"),
        F.col("mb.total_billed"),
        F.col("mb.admits_from_ed"),
        F.col("mb.avg_conditions_per_visit"),
        F.col("tc.top_condition")
    )
)

# =========================================
# Write to target Delta table (overwrite as batch pipeline)
# =========================================
spark.sql("CREATE SCHEMA IF NOT EXISTS agentops.gold")
final_df.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("agentops.gold.ed_utilization_monthly")

# =========================================
# Display sample for validation
# =========================================
display(final_df.limit(20))