# Databricks notebook source
# Generated by Agent 03A for DBXCOE-36 | plan 0f5e19fa217c70e2 | tests a62c1e85f767a198 | attempt 1 | 2026-10-07T03:51:04.123622+00:00
# Plan approved by system:auto_approve (auto_approved)
# Based on existing file: /Workspace/Repos/sweta.mohapatra@ascendion.com/agentops-demo/pipelines/tests/dry_run_rejected_claims_patient_summary

# COMMAND ----------

# COMMAND ----------
from pyspark.sql import functions as F, DataFrame
from pyspark.sql import Window  # CHANGED (DBXCOE-36): Import Window at module scope to avoid UnboundLocalError
dbutils.widgets.text("target_catalog", "agentops")
dbutils.widgets.text("target_schema", "gold")
dbutils.widgets.text("run_mode", "run")   # "library" = only define functions (tests import the notebook this way)
TARGET_CATALOG = dbutils.widgets.get("target_catalog"); TARGET_SCHEMA = dbutils.widgets.get("target_schema"); RUN_MODE = dbutils.widgets.get("run_mode")

# COMMAND ----------
def build(spark, sources: dict) -> dict:
    # sources keys: ['claim', 'patient'] (DataFrames with the bronze schema)
    # returns a dict with EXACTLY these keys and columns:
    # "rejected_claims_patient_summary": one row per patient_id; columns [patient_id, gender, state, rejected_claim_count, total_rejected_amount, most_recent_rejection_date]
    # CHANGED (DBXCOE-36): Implement patient-level summary of denied claims per clarified business rules

    # Input aliases
    c = sources["claim"].alias("c")
    p = sources["patient"].alias("p")

    # CHANGED (DBXCOE-36): Deduplicate sources on their primary keys before joining
    # Business rule: claims and patients may have duplicates; keep the latest ingested per key
    c_dedup = (
        c.select(
            F.col("c.claim_id").alias("claim_id"),
            F.col("c.status").alias("status"),
            F.col("c.claim_type").alias("claim_type"),
            F.col("c.patient_id").alias("patient_id"),
            F.col("c.provider_id").alias("provider_id"),
            F.col("c.encounter_id").alias("encounter_id"),
            F.col("c.billable_start").alias("billable_start"),
            F.col("c.billable_end").alias("billable_end"),
            F.col("c.total_value").alias("total_value"),
            F.col("c.total_currency").alias("total_currency"),
            F.col("c._source_file").alias("_source_file"),
            F.col("c._ingested_at").alias("_ingested_at"),
        )
        .where(F.col("patient_id").isNotNull())  # CHANGED (DBXCOE-36): Only claims with a patient_id
        .withColumn("_rn", F.row_number().over(Window.partitionBy("claim_id").orderBy(F.col("_ingested_at").desc_nulls_last())))
        .where(F.col("_rn") == 1)
        .drop("_rn")
        .alias("c")
    )

    p_dedup = (
        p.select(
            F.col("p.patient_id").alias("patient_id"),
            F.col("p.mrn").alias("mrn"),
            F.col("p.last_name").alias("last_name"),
            F.col("p.first_name").alias("first_name"),
            F.col("p.gender").alias("gender"),
            F.col("p.birth_date").alias("birth_date"),
            F.col("p.postal_code").alias("postal_code"),
            F.col("p.state").alias("state"),
            F.col("p.active").alias("active"),
            F.col("p._source_file").alias("_source_file"),
            F.col("p._ingested_at").alias("_ingested_at"),
        )
        .withColumn("_rn", F.row_number().over(Window.partitionBy("patient_id").orderBy(F.col("_ingested_at").desc_nulls_last())))
        .where(F.col("_rn") == 1)
        .drop("_rn")
        .alias("p")
    )

    # CHANGED (DBXCOE-36): Filter to denied claims only per Q1 (lower(status) = 'denied')
    denied = (
        c_dedup.where(F.lower(F.col("c.status")) == F.lit("denied"))
        .alias("c")
    )

    # CHANGED (DBXCOE-36): Join only to active patients per Q5 (lower(active) = 'true')
    active_patients = (
        p_dedup.where(F.lower(F.col("p.active")) == F.lit("true"))
        .alias("p")
    )

    # CHANGED (DBXCOE-36): Join claims to patients on patient_id; explicit null handling ensured by prior filters
    joined = (
        denied.join(active_patients, on=F.col("c.patient_id") == F.col("p.patient_id"), how="inner")
        .select(
            F.col("c.claim_id").alias("c_claim_id"),
            F.col("c.patient_id").alias("patient_id"),
            F.col("p.gender").alias("gender"),
            F.col("p.state").alias("state"),
            F.col("c.billable_start").alias("billable_start"),
            F.col("c.total_value").alias("total_value"),
            F.col("c.total_currency").alias("total_currency"),
        )
        .alias("j")
    )

    # CHANGED (DBXCOE-36): Parse timestamps safely in ANSI mode; billable_start is ISO 8601
    j_parsed = (
        joined.withColumn(
            "billable_start_ts",
            F.coalesce(
                F.expr("try_to_timestamp(billable_start)"),
                F.lit(None).cast("timestamp"),
            ),
        )
        .alias("jp")
    )

    # CHANGED (DBXCOE-36): Exclude non-USD or null currency from amount aggregation per Q10
    j_amt = (
        j_parsed.withColumn(
            "amount_usd",
            F.when(F.col("total_currency") == F.lit("USD"), F.col("total_value")).otherwise(F.lit(None).cast("double")),
        ).alias("ja")
    )

    # CHANGED (DBXCOE-36): Aggregate to one row per patient_id (intended grain) with required metrics and dimensions
    # - rejected_claim_count = count(distinct claim_id) per patient
    # - total_rejected_amount = sum of USD amounts; cast to decimal(18,2) for money
    # - most_recent_rejection_date = max(billable_start)
    agg = (
        j_amt.groupBy(F.col("patient_id"), F.col("gender"), F.col("state"))
        .agg(
            F.countDistinct(F.col("c_claim_id")).alias("rejected_claim_count"),
            F.sum(F.col("amount_usd")).cast("decimal(18,2)").alias("total_rejected_amount"),
            F.max(F.col("billable_start_ts")).alias("most_recent_rejection_date"),
        )
        .alias("out")
    )

    outputs = {
        "rejected_claims_patient_summary": agg.select(
            F.col("patient_id"),
            F.col("gender"),
            F.col("state"),
            F.col("rejected_claim_count"),
            F.col("total_rejected_amount"),
            F.col("most_recent_rejection_date"),
        )
    }
    return outputs

# COMMAND ----------
def load_sources(spark) -> dict:
    return {
        "claim": spark.table("agentops.silver.claim"),
        "patient": spark.table("agentops.silver.patient"),
    }

# COMMAND ----------
if RUN_MODE == "run" and not globals().get("AGENTOPS_LIBRARY_MODE", False):
    outputs = build(spark, load_sources(spark))
    spark.sql(f"CREATE SCHEMA IF NOT EXISTS {TARGET_CATALOG}.{TARGET_SCHEMA}")
    for name, df in outputs.items():
        df.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(f"{TARGET_CATALOG}.{TARGET_SCHEMA}.{name}")