# Databricks notebook source
# Generated by Agent 03A for DBXCOE-35 | plan 7da0b9a77794fa46 | tests 65b05e1e88aef898 | attempt 0 | 2026-10-06T22:44:52.116848+00:00
# Plan approved by sweta.mohapatra@ascendion.com (human_approved)

# COMMAND ----------

# COMMAND ----------
from pyspark.sql import functions as F, DataFrame
try:
    import dlt
except ImportError:      # tests import this notebook outside a pipeline
    dlt = None

# COMMAND ----------
def build(spark, sources: dict) -> dict:
    # Output grain: one row per patient_id
    # BUSINESS RULES:
    # - Include only patients with active = 'true' (case-insensitive)
    # - Include only denied claims (status = 'denied', case-insensitive)
    # - Exclude claims with null patient_id
    # - Inner join active patients to denied claims so only patients with at least one denied claim appear
    # - Patient attributes (patient_name, gender, state) sourced solely from patient
    # - Patient name: coalesce + trim + collapse multiple spaces; never drop rows due to nulls
    # - last_denial_date: max of billable_start cast to DATE using ANSI-safe try_cast; keep nulls (do not drop)
    # - Metrics:
    #     total_denied_claims: count of claim_id (duplicates count as provided)
    #     total_denied_amount: sum of total_value; widen to decimal(18,2)

    claim_src = sources["claim"]
    patient_src = sources["patient"]

    # Deduplicate on primary keys prior to join
    # Claims primary key: claim_id (assumed unique in source; keep duplicates as data if claim_id duplicates exist per acceptance test)
    # Here we DO NOT deduplicate claims because the spec explicitly allows duplicate denied claim rows to contribute to counts/sums.
    c = (
        claim_src
        .where(F.col("patient_id").isNotNull())  # Exclude claims where patient_id is null
        .withColumn("status_l", F.lower(F.col("status")))
        .where(F.col("status_l") == F.lit("denied"))  # Filter denied claims
        .drop("status_l")
        .alias("c")
    )

    # Patients: keep only active = 'true' (case-insensitive); deduplicate on patient_id
    p_active = (
        patient_src
        .withColumn("active_l", F.lower(F.col("active")))
        .where(F.col("active_l") == F.lit("true"))
        .drop("active_l")
        .dropDuplicates(["patient_id"])
        .alias("p")
    )

    # Patient name construction: COALESCE + TRIM + collapse multiple spaces
    # Implement as a projection on patient side prior to join
    p_named = (
        p_active
        .withColumn("first_n", F.when(F.trim(F.col("first_name")) == F.lit(""), F.lit(None)).otherwise(F.col("first_name")))
        .withColumn("last_n", F.when(F.trim(F.col("last_name")) == F.lit(""), F.lit(None)).otherwise(F.col("last_name")))
        .withColumn("patient_name_raw", F.concat_ws(" ", F.col("first_n"), F.col("last_n")))
        .withColumn("patient_name_trim", F.trim(F.coalesce(F.col("patient_name_raw"), F.lit(""))))
        .withColumn("patient_name", F.regexp_replace(F.col("patient_name_trim"), r"\s{2,}", " "))
        .drop("first_n", "last_n", "patient_name_raw", "patient_name_trim")
        .alias("p")
    )

    # Prepare claim date casting using ANSI-safe try_cast for DATE
    c_typed = (
        c
        .withColumn("billable_start_ts", F.coalesce(
            F.expr("try_to_timestamp(billable_start)"),
            F.expr("try_to_timestamp(billable_start, 'yyyy-MM-dd''T''HH:mm:ssXXX')")  # secondary pattern if present
        ))
        .withColumn("billable_start_date", F.expr("try_cast(billable_start_ts AS DATE)"))
        .alias("c")
    )

    # Inner join: only active patients with denied claims
    joined = (
        p_named.join(c_typed, on=F.col("p.patient_id") == F.col("c.patient_id"), how="inner")
    )

    # Aggregate metrics at patient_id grain; widen types for safe aggregation
    # total_denied_amount as decimal(18,2)
    agg = (
        joined.groupBy(F.col("p.patient_id"))
        .agg(
            F.max(F.col("p.patient_name")).alias("patient_name"),
            F.max(F.col("p.gender")).alias("gender"),
            F.max(F.col("p.state")).alias("state"),
            F.max(F.col("c.billable_start_date")).alias("last_denial_date"),
            F.count(F.col("c.claim_id")).alias("total_denied_claims"),
            F.sum(F.col("c.total_value").cast("decimal(18,2)")).alias("total_denied_amount")
        )
        .select(
            F.col("patient_id"),
            F.col("patient_name"),
            F.col("gender"),
            F.col("state"),
            F.col("last_denial_date"),
            F.col("total_denied_claims"),
            F.col("total_denied_amount")
        )
    )

    return {
        "gold_rejected_claims_patient_summary_v2": agg
    }

# COMMAND ----------
def load_sources(spark) -> dict:
    return {
        "claim": spark.read.table("agentops.bronze.claim"),
        "patient": spark.read.table("agentops.bronze.patient"),
    }

# COMMAND ----------
if dlt is not None and not globals().get("AGENTOPS_LIBRARY_MODE", False):
    @dlt.table(
        name="gold_rejected_claims_patient_summary_v2",
        comment="Materialized view summarizing denied claims by patient with patient attributes and denial metrics; grain: one row per patient_id"
    )
    @dlt.expect_or_drop("not_null_patient_id", "patient_id IS NOT NULL")
    def gold_rejected_claims_patient_summary_v2():
        return build(spark, load_sources(spark))["gold_rejected_claims_patient_summary_v2"]