# Databricks notebook source
# Generated by Agent 03A for DBXCOE-33 | plan af8236763d6e0157 | tests 461ad20b33199e63 | attempt 1 | 2026-10-06T06:09:43.302482+00:00
# Plan approved by system:auto_approve (auto_approved)

# COMMAND ----------

from pyspark.sql import functions as F, DataFrame
dbutils.widgets.text("target_catalog", "agentops")
dbutils.widgets.text("target_schema", "gold")
dbutils.widgets.text("run_mode", "run")   # "library" = only define functions (tests import the notebook this way)
TARGET_CATALOG = dbutils.widgets.get("target_catalog"); TARGET_SCHEMA = dbutils.widgets.get("target_schema"); RUN_MODE = dbutils.widgets.get("run_mode")

# COMMAND ----------

# DBTITLE 1,Implementation
def _prepare_claims(df: DataFrame) -> DataFrame:
    # Business rule: Only consider rejected claims → status = 'denied'
    # Business rule: Exclude claims without linked patient_id or claim_id (patient-centric and dedup key)
    # Business rule: Deduplicate on claim_id → count each rejected claim once
    # Business rule: Parse billable_start (ISO 8601 per profile) for most recent rejection date
    claims = (
        df
        .withColumn("billable_start_ts", F.expr("try_to_timestamp(billable_start)"))
        .filter(F.col("status").isin("denied", "rejected"))
        .filter(F.col("patient_id").isNotNull())
        .filter(F.col("claim_id").isNotNull())
    )
    # Keep latest by _ingested_at per claim_id to deduplicate
    from pyspark.sql import Window
    w = Window.partitionBy(F.col("claim_id")).orderBy(F.col("_ingested_at").desc_nulls_last())
    claims_dedup = (
        claims
        .withColumn("_rn", F.row_number().over(w))
        .filter(F.col("_rn") == F.lit(1))
        .drop("_rn")
        .alias("clm")
    )
    return claims_dedup

def _prepare_patients(df: DataFrame) -> DataFrame:
    # Business rule: patient_id is the unique identifier; deduplicate on patient_id
    # Business rule: Keep gender and state demographics
    from pyspark.sql import Window
    w = Window.partitionBy(F.col("patient_id")).orderBy(F.col("_ingested_at").desc_nulls_last())
    patients = (
        df
        .filter(F.col("patient_id").isNotNull())
        .withColumn("_rn", F.row_number().over(w))
        .filter(F.col("_rn") == F.lit(1))
        .drop("_rn")
        .select(
            F.col("patient_id"),
            F.col("gender"),
            F.col("state")
        )
        .alias("pat")
    )
    return patients

def build(spark, sources: dict) -> dict:
    # sources keys: ['claim', 'patient']
    clm_src = sources["claim"]
    pat_src = sources["patient"]

    # Prepare sources per business rules
    clm = _prepare_claims(clm_src)
    pat = _prepare_patients(pat_src)

    # Business rule: Inner join to exclude claims without a valid patient row
    joined = (
        clm.join(pat, on=[clm.patient_id == pat.patient_id], how="inner")
        .select(
            F.coalesce(clm.patient_id, pat.patient_id).alias("patient_id"),
            pat.gender,
            pat.state,
            clm.billable_start_ts,
            clm.total_value
        )
        .alias("j")
    )

    # Business rule: Aggregate at patient-level
    # - rejected_claim_count: count of distinct rejected claims per patient (after claim_id dedup) → count rows
    # - total_rejected_amount: sum of total_value (money metric should be decimal(18,2))
    # - most_recent_rejection_date: max of billable_start
    agg = (
        joined.groupBy("patient_id", "gender", "state")
        .agg(
            F.count(F.lit(1)).cast("long").alias("rejected_claim_count"),
            F.sum(F.col("total_value")).cast("decimal(18,2)").alias("total_rejected_amount"),
            F.max(F.col("billable_start_ts")).alias("most_recent_rejection_date")
        )
    )

    rejected_claims_patient_summary = (
        agg.select(
            F.col("patient_id"),
            F.col("gender"),
            F.col("state"),
            F.col("rejected_claim_count"),
            F.col("total_rejected_amount"),
            F.col("most_recent_rejection_date")
        )
    )

    return {
        "rejected_claims_patient_summary": rejected_claims_patient_summary
    }

# COMMAND ----------

def load_sources(spark) -> dict:
    return {
        "claim": spark.table("agentops.bronze.claim"),
        "patient": spark.table("agentops.bronze.patient"),
    }

# COMMAND ----------

if RUN_MODE == "run" and not globals().get("AGENTOPS_LIBRARY_MODE", False):
    outputs = build(spark, load_sources(spark))
    spark.sql(f"CREATE SCHEMA IF NOT EXISTS {TARGET_CATALOG}.{TARGET_SCHEMA}")
    for name, df in outputs.items():
        df.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(f"{TARGET_CATALOG}.{TARGET_SCHEMA}.{name}")